name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Generate deployment package
        run: |
          zip -r deploy.zip . -x "*.git*" "node_modules/*" "src/*"
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Wait for environment to be ready
        run: |
          MAX_ATTEMPTS=30
          ATTEMPT=1
          while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
            STATUS=$(aws elasticbeanstalk describe-environments --environment-names Blog-magician-api-prod --query "Environments[0].Status" --output text)
            if [ "$STATUS" = "Ready" ]; then
              echo "Environment is ready"
              break
            fi
            echo "Environment status is $STATUS, waiting... (Attempt $ATTEMPT of $MAX_ATTEMPTS)"
            sleep 10
            ATTEMPT=$((ATTEMPT + 1))
          done
          if [ $ATTEMPT -gt $MAX_ATTEMPTS ]; then
            echo "Environment did not become ready in time"
            exit 1
          fi

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: blog-magician
          environment_name: Blog-magician-api-prod
          region: ${{ secrets.AWS_REGION }}
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          use_existing_version_if_available: true